### PR TITLE
GitHub Actions sub-generator

### PR DESCRIPTION
**Pull request by rajyraman**
1. Updated Workflow yaml. Solution files are now under src/Other.
2. Added Actions to docs.

### CODE REVIEW

**Comment by DynamicsNinja** [comment]
Thanks for the PR! I was struggling to finish my version of the GitHub action sub-generator with a little bit different approach.

The only issue with this one is the folder structure for solutions. The generator is creating folder structure without control name as a subfolder, so if someone inits the project via generator the action will not work straight away. Need to check also with Danish how he handles the build command in PCF builder extension so we don't break his tool too.

I would be happy to jump on a call with you to discuss this action because I'm big ALM noob.

**Comment by rajyraman** [comment]
The reason I created a generic Solution folder and put the component name as sub-folder is because when you do the pac solution it takes the folder name as the Soluton name. I have also just kept this as a convention. Ideally @Power-Maverick , you and I need to use the same structure so that there are no conflicts.

**Comment by Power-Maverick** [comment]
I literally thought about this yesterday @DynamicsNinja. In PCF Builder I am using Solution folder with Control name as sub-folder for XrmToolbox version. I agree with @rajyraman we can all align on the folder structure which will make a seamless experience.
Let me confirm if I am using singular or plural name of _Solution_

**Comment by DynamicsNinja** [comment]
I would also like to align the conventions across all tools. The best & quickest way would be a call in my opinion so we can discuss all open questions there.

**Comment by Power-Maverick** [comment]
Ok so am using `Solutions` > `ControlName`
But now that I am thinking I should change it to singular because it will contain only one solution project.

**Pull request merged**
